name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  job-with-github-action-repo: # tên của job
    runs-on: ubuntu-latest # môi trường chạy
    steps:
      - run: |
          chmod +x ./example.sh
          ./example.sh
        shell: bash