name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setting up"
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: "building app"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: "testing"